### ISSUE TITLE
Where does the __adaptor__.addStepDefinitions go?

### ISSUE THREAD

**Issue by ghost** [eugene-sea/karma-cucumber-js#10]
Hi, thanks for the adaptor. It's not clear from the  documentation where the addStepDefinitions function should go, does it go inside the karma.conf.js?

**Comment by eugene-sea** [comment]
They should go into your step definitions files. I have updated [README.md](https://github.com/eugene-sea/karma-cucumber-js/blob/master/README.md).

**Comment by ghost** [comment]
Cool thanks.
