### ISSUE TITLE
Please add steps on how to build the package

### ISSUE THREAD

**Issue by jfstephe** [eugene-sea/karma-cucumber-js#16]
As mentioned in PR #17, I had trouble generating all the js files. Can you add steps to help contributors to the readme or add a script to do the steps and reference that in the readme?
Many thanks.

**Comment by eugene-sea** [comment]
I have published new version with your changes and updated `README.md` with building instructions

**Comment by jfstephe** [comment]
Doh - should have looked there! Thanks.
