### ISSUE TITLE
Resolve path (or parttern) 'tests/*.js'

### ISSUE THREAD

**Issue by TNNSon** [eugene-sea/karma-cucumber-js#4]
Hi!
I clone your source, but can't build and tests

**Comment by eugene-sea** [comment]
Could you post complete shell output? Which OS do you use? I have tested building only on Mac, so on Windows issues may be present.

**Comment by TNNSon** [comment]
My OS is Windows
Here is issue
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! karma-cucumber-js@0.3.0 build: `./scripts/build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the karma-cucumber-js@0.3.0 build script './scripts/build.sh'.
npm ERR! This is most likely a problem with the karma-cucumber-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/build.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs karma-cucumber-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls karma-cucumber-js
npm ERR! There is likely additional logging output above.

**Comment by eugene-sea** [comment]
Could you retry now? I have pushed fix

**Comment by TNNSon** [comment]
thanks you so much, it's work
