### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by JimLynchCodes** [eugene-sea/karma-cucumber-js#9]
Is there an example of a project using this framework with a sample feature, step, and karma.config file that I can looks at? Thanks!

**Comment by eugene-sea** [comment]
https://github.com/eugene-sea/karma-cucumber-js/blob/master/karma.conf.js
https://github.com/eugene-sea/karma-cucumber-js/tree/master/test_features

Note, karma.conf.js should be exactly like in [README.md](https://github.com/eugene-sea/karma-cucumber-js/blob/master/README.md)

**Comment by JimLynchCodes** [comment]
Thanks!
